In [7]:
import numpy as np

In [8]:
#s1 = [[-1,1,1],[1,-1,-1],[1,-1,-1],[1,-1,-1],[-1,1,1]]     PATTERN C
#s2 = [[1,-1,1],[1,-1,1],[-1,1,-1],[1,-1,1],[1,-1,1]]       PATTERN X

s1 = [[-1,1,1],[1,-1,-1],[1,-1,-1],[1,-1,-1],[-1,1,1]]
t1 = 1
s2 = [[1,-1,1],[1,-1,1],[-1,1,-1],[1,-1,1],[1,-1,1]]
t2 = -1
w0 = 0
b0 = 0

In [9]:
# Concatenated components of the input patterns columnwise
s1 = np.array(s1)
s1 = s1.T
s1 = s1.reshape(1,-1)
s1 = s1[0]
s2 = np.array(s2)
s2 = s2.T
s2 = s2.reshape(1,-1)
s2 = s2[0]
s1_temp = list(s1)
s1_temp = s1_temp[:]
print (s1)
print (s2)

[-1  1  1  1 -1  1 -1 -1 -1  1  1 -1 -1 -1  1]
[ 1  1 -1  1  1 -1 -1  1 -1 -1  1  1 -1  1  1]


In [4]:
# Training the NN with the weight and bias only once (fixed for the rest of the flipped / undetermined patterns) 
w = w0 + np.array(s1)*t1 + np.array(s2)*t2
w = w.reshape(1,-1)
#w = w[0]
b = b0 + t1 + t2
print (w)
print (b)

[[-2  0  2  0 -2  2  0 -2  0  2  0 -2  0 -2  0]]
0


In [5]:
# Flipped pixels case:
from itertools import combinations
s1_temp = list(s1)
s1_temp = s1_temp[:]
s1_temp
s2 = list(s2)
l1 = []
s1_temporary = s1_temp[:]
for k in range(0,len(s1_temp)+1):
    combination = list(combinations(range(len(s1_temp)),k))
    s1_temporary = s1_temp[:]
    l2 = []
    misclassified = 0
    mis = []
    for comb in combination:
        s1_temporary = s1_temp[:]
        for ele in comb:
            s1_temporary[ele] = -s1_temporary[ele]
        l2.append(s1_temporary)
        yin1 = np.matmul(s1_temporary,w.T) + b
        o1 = yin1[0]
        yin2 = np.matmul(s2,w.T) + b
        o2 = yin2[0]
        if o1 > 0:
            t1_pred = 1
        elif o1 < 0:
            t1_pred = -1
        else:
            t1_pred = 0
        if o2 > 0:
            t2_pred = 1
        elif o2 < 0 :
            t2_pred = -1
        else:
            t2_pred = 0
            
        if not((t1 == t1_pred) and (t2==t2_pred)):
            misclassified += 1
            mis.append(s1_temporary)
            
    print ('For k = {}, misclassified = {}'.format(k,misclassified))
    #print (mis) # prints all the misclassified vectors for each k

    l1.append(l2)

For k = 0, misclassified = 0
For k = 1, misclassified = 0
For k = 2, misclassified = 0
For k = 3, misclassified = 0
For k = 4, misclassified = 70
For k = 5, misclassified = 546
For k = 6, misclassified = 1890
For k = 7, misclassified = 3830
For k = 8, misclassified = 5055
For k = 9, misclassified = 4585
For k = 10, misclassified = 2947
For k = 11, misclassified = 1365
For k = 12, misclassified = 455
For k = 13, misclassified = 105
For k = 14, misclassified = 15
For k = 15, misclassified = 1


In [6]:
# Undetermined pixels case:
from itertools import combinations
s1_temp = list(s1)
s1_temp = s1_temp[:]
s1_temp
s2 = list(s2)
l1 = []
s1_temporary = s1_temp[:]
for k in range(0,len(s1_temp)+1):
    combination = list(combinations(range(len(s1_temp)),k))
    s1_temporary = s1_temp[:]
    l2 = []
    misclassified = 0
    mis = []
    for comb in combination:
        s1_temporary = s1_temp[:]
        for ele in comb:
            s1_temporary[ele] = 0
        l2.append(s1_temporary)
        yin1 = np.matmul(s1_temporary,w.T) + b
        o1 = yin1[0]
        yin2 = np.matmul(s2,w.T) + b
        o2 = yin2[0]
        if o1 > 0:
            t1_pred = 1
        elif o1 < 0:
            t1_pred = -1
        else:
            t1_pred = 0
        if o2 > 0:
            t2_pred = 1
        elif o2 < 0 :
            t2_pred = -1
        else:
            t2_pred = 0
        if not((t1 == t1_pred) and (t2==t2_pred)):
            misclassified += 1
            mis.append(s1_temporary)
    print ('For k = {}, misclassified = {}'.format(k,misclassified))
    print (mis) # prints all the misclassified vectors for each k
    l1.append(l2)

For k = 0, misclassified = 0
[]
For k = 1, misclassified = 0
[]
For k = 2, misclassified = 0
[]
For k = 3, misclassified = 0
[]
For k = 4, misclassified = 0
[]
For k = 5, misclassified = 0
[]
For k = 6, misclassified = 0
[]
For k = 7, misclassified = 0
[]
For k = 8, misclassified = 1
[[0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 1, 0, -1, 0, 1]]
For k = 9, misclassified = 7
[[0, 0, 0, 1, 0, 0, -1, 0, -1, 0, 1, 0, -1, 0, 1], [0, 1, 0, 0, 0, 0, -1, 0, -1, 0, 1, 0, -1, 0, 1], [0, 1, 0, 1, 0, 0, 0, 0, -1, 0, 1, 0, -1, 0, 1], [0, 1, 0, 1, 0, 0, -1, 0, 0, 0, 1, 0, -1, 0, 1], [0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 0, 0, -1, 0, 1], [0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 1, 0, 0, 0, 1], [0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 1, 0, -1, 0, 0]]
For k = 10, misclassified = 21
[[0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 1, 0, -1, 0, 1], [0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 1, 0, -1, 0, 1], [0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 1, 0, -1, 0, 1], [0, 0, 0, 1, 0, 0, -1, 0, -1, 0, 0, 0, -1, 0, 1], [0, 0, 0, 1, 0, 0, -1, 0, -1, 0, 1, 0, 0, 0, 1], [0, 0, 0