In [0]:
# Importing the necessary Libraries
import numpy as np
import random

In [0]:
# Training Set
S = np.array([[1, 1, -1, -1, -1, 1], [1, -1, -1, 1, -1, -1], [-1, -1, 1, 1, 1, -1], [-1, 1, 1, -1, 1, 1]]).reshape(4,-1)
#S

In [3]:
# Weight Matrix Calculation using Hebb's rule
W = np.array(np.zeros((6,6)))
for i in range(len(S)):
  W = W + S[i].reshape(-1,1) * S[i].reshape(1,-1)
W

array([[ 4.,  0., -4.,  0., -4.,  0.],
       [ 0.,  4.,  0., -4.,  0.,  4.],
       [-4.,  0.,  4.,  0.,  4.,  0.],
       [ 0., -4.,  0.,  4.,  0., -4.],
       [-4.,  0.,  4.,  0.,  4.,  0.],
       [ 0.,  4.,  0., -4.,  0.,  4.]])

In [4]:
# Diagonal Elements of the Weight Matrix set to Zero as there are no Self Connections
for i in range(6):
  W[i,i]=0
W

array([[ 0.,  0., -4.,  0., -4.,  0.],
       [ 0.,  0.,  0., -4.,  0.,  4.],
       [-4.,  0.,  0.,  0.,  4.,  0.],
       [ 0., -4.,  0.,  0.,  0., -4.],
       [-4.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  4.,  0., -4.,  0.,  0.]])

In [5]:
# Computation of Net Input (yin) and Updation of activations using the fHopfield Transfer Function
orders = range(S.shape[1])
random.shuffle(orders)     # Neurons are updated randomly and asynchronously
for i in range(S.shape[0]):
  y = [0 for j in range(S.shape[1])]
  s = S[i].reshape(1,-1)
  for order in orders:
    y[order] = s[0][order] + np.dot(s,(W[:,order].reshape(6,1)))[0][0]
  y = np.array(y)
  # fHopfield Transfer Function with Threshold kept as Zero
  y[y>0]=1
  y[y<0]=-1
#   print s[0]
  for j in range(len(y)):
    if y[j]==0:
      y[j] = s[0][j]
  print y     #All four stored patterns are equilibrium states of the system as can be seen
# Training part ends  
  

[ 1.  1. -1. -1. -1.  1.]
[ 1. -1. -1.  1. -1. -1.]
[-1. -1.  1.  1.  1. -1.]
[-1.  1.  1. -1.  1.  1.]


In [0]:
S=S.tolist()
#S

In [7]:
# Testing Part
# Taking all combinations of Bipolar vectors as Test Vectors
from itertools import combinations

all_input = []

vec = range(6)
all_states = []
for k in range(7):

  comb = list(combinations(vec,k))

  for combination in comb:
    temp = [1 for i in range(6)]
    for ele in combination:
      temp[ele] = -1
    all_states.append(temp)
        
all_states = np.array(all_states)

all_states.shape    # There are 64 different Bipolar Vectors

(64, 6)

In [0]:
equi_states = []      # "List" holding all equillibrium states of the system 
spurious_states = []   # "List" holding all spurious states of the system

In [0]:
from collections import defaultdict
basins = defaultdict(list)       # This holds all the basins of attractions

In [0]:
# Getting the list of all equilibrium states, basin of attractions and spurious states of the system
basins = dict((i,[]) for i in range(4))

for i in range(all_states.shape[0]):
  y = [0 for j in range(all_states.shape[1])]
  s = all_states[i].reshape(1,-1)
  for order in orders:
    y[order] = s[0][order] + np.dot(s,(W[:,order].reshape(6,1)))[0][0]
  y = np.array(y)
  y[y>0]=1
  y[y<0]=-1
  for j in range(len(y)):
    if y[j]==0:
      y[j] = s[0][j]
  y = y.tolist()
  if y in S:
    equi_states.append(y)
    for j in range(len(S)):
      if y == S[j]:
        basins[j].append(y)
        break
  else:
    spurious_states.append(y)

In [11]:
equi_states # List of all the equillibrium states of the system

[[-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0]

In [12]:
spurious_states # List of all the spurious states of the system

[]

In [13]:
reverse_states = []  # "List" holding all the equillibrium states of the system that can be considered reversed states

for ele in equi_states:
  if ele[::-1] in all_states:
    reverse_states.append(ele)
reverse_states    # Empty because we do not have any equillibrium states that can be considered as reversed states of something else

[[-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0]

In [14]:
basins[0] # List of all the equillibrium states of the system that have the 1st training vector [1, 1, -1, -1, -1, 1] as the basin of attraction

[[1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
 [1.0, 1.0, -1.0, -1.0, -1.0, 1.0]]

In [15]:
basins[1] # List of all the equillibrium states of the system that have the 2nd training vector [1, -1, -1, 1, -1, -1] as the basin of attraction

[[1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0],
 [1.0, -1.0, -1.0, 1.0, -1.0, -1.0]]

In [16]:
basins[2] # List of all the equillibrium states of the system that have the 3rd training vector [-1, -1, 1, 1, 1, -1] as the basin of attraction

[[-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
 [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0]]

In [17]:
basins[3] # List of all the equillibrium states of the system that have the 4th training vector [-1, 1, 1, -1, 1, 1] as the basin of attraction

[[-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0],
 [-1.0, 1.0, 1.0, -1.0, 1.0, 1.0]]

In [18]:
chance = len(spurious_states)*100.0/all_states.shape[0]
chance # The chance that an input pattern does not associate with any of the stored pattern 

0.0